### ISSUE TITLE
I have no idea how to use this

### ISSUE THREAD

**Issue by ouija** [hi019/vivint.js#2]
Likke the title says:  I have _no idea_ what the heck I'm doing when it comes to node.js and how to make this work (it's completely foreign to me unfortunatly) Basically I've installed Node.js/NPM under a Ubuntu 20.04 VM and ran `npm install vivint.js` and it installed, then I cloned this repo and edited `examples/rtsp-stream.ts` to include `vivint.js` but get the following errors:

```
rtsp-stream.ts:1:25 - error TS2307: Cannot find module 'vivint.js'.

1 import * as Vivint from 'vivint.js'; // In your code, import from `vivint.js` instead
                          ~~~~~~~~~~~

rtsp-stream.ts:2:30 - error TS2307: Cannot find module 'vivint.js'.

2 import { DEVICE_TYPES } from 'vivint.js';
                               ~~~~~~~~~~~

rtsp-stream.ts:3:20 - error TS2307: Cannot find module 'colors'.

3 import colors from 'colors';
                     ~~~~~~~~

rtsp-stream.ts:5:14 - error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.

5 const main = async () => {
               ~~~~~~~~~~~~~


Found 5 errors.
```

I'm too inept at this to even know how to make use of this -- I really just want to figure out a way to get the RTSP authentication from my Vivint system so I can access the streams.

**Comment by hi019** [comment]
You need to clone the project then do `npm install` (not `npm install vivint.js`) inside the cloned project. There are more detailed instructions [here](https://github.com/hi019/vivint.js/wiki/Getting-RTSP-Streams#how-to-obtain-an-rtsp-stream). Make sure you do `cd vivint.js` in between step 1 and 2.

**Comment by ouija** [comment]
Dang it, apologies.  Didn't even look at the wiki, my bad, and my inexperience with Node is showing in that I neglected to realize I have to install the dependancies..   I'll let you know how it goes, and thank you for your help!

**Comment by hi019** [comment]
No problem

**Comment by ouija** [comment]
OK, managed to get further than before.  Fresh install of node/npm and followed the wiki to the letter, but when running `npx ts-node examples/rtsp-stream.ts` I'm getting the follow error:

```
(node:18740) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of undefined
    at new Camera (/home/ryan/Desktop/vivint.js/src/resources/camera.ts:46:35)
    at devices.map (/home/ryan/Desktop/vivint.js/src/resources/panel.ts:90:32)
    at Array.map (<anonymous>)
    at Panel.getDevices (/home/ryan/Desktop/vivint.js/src/resources/panel.ts:86:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:18740) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18740) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by hi019** [comment]
I have just pushed an update, it will still error but will provide more context. You'll have to repeat the steps, and then paste the output here.

**Comment by ouija** [comment]
```
(node:21664) UnhandledPromiseRejectionWarning: Error: Could not extract camera ID (cea: undefined): TypeError: Cannot read property 'match' of undefined
    at new Camera (/home/ryan/Desktop/vivint.js/src/resources/camera.ts:51:19)
    at devices.map (/home/ryan/Desktop/vivint.js/src/resources/panel.ts:90:32)
    at Array.map (<anonymous>)
    at Panel.getDevices (/home/ryan/Desktop/vivint.js/src/resources/panel.ts:86:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:21664) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21664) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by hi019** [comment]
Whoops, my last commit wouldn't of helped. I've pushed another change

**Comment by hi019** [comment]
To speed up the process, you can just copy the changed file (in this case `src/resources/camera.ts`) directly from github to your cloned repo, and then execute the example again

**Comment by ouija** [comment]
```
(node:22137) UnhandledPromiseRejectionWarning: Error: Could not extract camera ID: [object Object]
    at new Camera (/home/ryan/Desktop/vivint.js/src/resources/camera.ts:51:19)
    at devices.map (/home/ryan/Desktop/vivint.js/src/resources/panel.ts:90:32)
    at Array.map (<anonymous>)
    at Panel.getDevices (/home/ryan/Desktop/vivint.js/src/resources/panel.ts:86:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22137) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22137) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by hi019** [comment]
Shoot, forgot to serialize the object. Well I'm gonna go to bed now, will solve in the morning.

**Comment by ouija** [comment]
```
(node:22474) UnhandledPromiseRejectionWarning: Error: Could not extract camera ID: {"cous":"rtsp://10.202.242.68:8554/Video-35_SD","ceu":["rtsp://livevid.vivint.com:443/xxx/8554/Video-35"],"cetus":["rtsp://v.vivintsky.com:443/xxxx/8554/Video-35_SD"],"pswd":"xxxx","ciu":["rtsp://192.168.1.132:8554/Video-35"],"cius":["rtsp://192.168.1.132:8554/Video-35_SD"],"n":"Driveway","t":"camera_device","panid":xxx}
    at new Camera (/home/ryan/Desktop/vivint.js/src/resources/camera.ts:52:19)
    at devices.map (/home/ryan/Desktop/vivint.js/src/resources/panel.ts:90:32)
    at Array.map (<anonymous>)
    at Panel.getDevices (/home/ryan/Desktop/vivint.js/src/resources/panel.ts:86:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:22474) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22474) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ouija** [comment]
Got it working -  As you can tell, there is no `cea` value being returned for my streams, so I edited `src/resources/camera.ts` and replaced lines 45-54 with this  _(inlcuding the object serialization fix)_:

```
        // Extract camera id from audio url (camera id is used for things like retrieving streams)
        try {
            const cameraId = this.ciu[0].match(/\d+/);
            if (cameraId === null) throw new Error('Could not extract camera ID from cea');
            this.id = Number(cameraId[0]);
        } catch (e) {
            var jsonString = JSON.stringify(this);
            throw new Error(`Could not extract camera ID: ${jsonString}`);
        }
    }
```
Since I know that the IP value in `ciu` is what I'm after.

Then I also had to update `examples/rtsp-stream.ts` to also replace the instance of `ciu` with that of `cous`:
`const possiblePanelIp = cameras[0].cous.split('/')[2].slice(0, -5);`

And it's now working and returning my cameras RTSP streams urls! 👍 


One last question:  Do these passwords for the RTSP streams change after a certain period, or are they fairly static?  _(I suppose time will tell, but figured I'd ask the question if you knew)_  

Before a recent update to the Vivint Sky Panel, I was able to get the password by sniffing the network activity of the Android App (as it was exposed in plain text) but they recently changed that, and this is where your script came to the rescue, and I'm just wondering how dynamic this authentication is now...

Thanks again!   This script is *exactly* what I needed!

**Comment by hi019** [comment]
Nice! That's the thing about reverse engineered private API's -- you can only test them with your own account so the code may not work for everyone. 

> Do these passwords for the RTSP streams change after a certain period, or are they fairly static?

Mine recently changed after I initially found them several months ago. However they're easy to retrieve, just make an authenticated api request with your panel id:
 https://github.com/hi019/vivint.js/blob/master/src/resources/panel.ts#L63
