### ISSUE TITLE
Failed to parse file 'tsconfig.json'

### ISSUE THREAD

**Issue by jonpage88** [hi019/vivint.js#6]
I am trying to run npm install but I keep getting the following error:

error TS5014: Failed to parse file 'tsconfig.json': Unexpected token / in JSON at position 83.

I am not sure what my next step should be the fix this.

**Comment by hi019** [comment]
I'm not able to reproduce this issue, `npm init -y ; npm i vivint.js` works fine for me with an empty project. 

Also, this package's tsconfig.json only has 15 lines, so it may be an issue with your config

**Comment by jonpage88** [comment]
I ran that and that seemed to work but now when I am trying to run _npx ts-node examples/rtsp-stream.ts_ I am getting the following error:

/home/user1/vivint-camera/vivint.js/src/request.ts:37
    const pfToken = res.headers['set-cookie'][0].match(/PF=([^;]*)/)[1];
                                             ^
TypeError: Cannot read property '0' of undefined
    at Object.login (/home/user1/vivint-camera/vivint.js/src/request.ts:37:46)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at main (/home/user1/vivint-camera/vivint.js/examples/rtsp-stream.ts:6:5)

This might be something I am doing. I am not quite sure where to put the password in the rtsp-stream.ts file.

**Comment by hi019** [comment]
You'll need to replace 'username' and 'pass' on line 6 of the example code with your own credentials

**Comment by jonpage88** [comment]
Thanks. I am still getting the same error. I did the following to remove everything and recreate it but it didnt help.

1. Removed folder with project
2. Created new folder
3. Cloned project to folder: _git clone https://github.com/hi019/vivint.js.git_
4. Ran _npm init -y ; npm i vivint.js_ and got the following:

> Wrote to /home/autologin/vivint/package.json:
> 
> {
>   "name": "vivint",
>   "version": "1.0.0",
>   "description": "",
>   "main": "vivint.js",
>   "scripts": {
>     "test": "echo \"Error: no test specified\" && exit 1"
>   },
>   "keywords": [],
>   "author": "",
>   "license": "ISC"
> }
> 
> 
> npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
> npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
> npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
> npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
> 
> added 836 packages, and audited 837 packages in 17s
> 
> 32 packages are looking for funding
>   run `npm fund` for details
> 
> 2 high severity vulnerabilities
> 
> Some issues need review, and may require choosing
> a different dependency.
> 
> Run `npm audit` for details.
5. _cd vivint.js_
6. edited the example file: _nano examples/rtsp-stream.ts_ 
7. Ran _npx ts-node examples/rtsp-stream.ts_ and installed ts-node
8. got the following error message again:

> /home/autologin/vivint/vivint.js/src/request.ts:37
>     const pfToken = res.headers['set-cookie'][0].match(/PF=([^;]*)/)[1];
>                                              ^
> TypeError: Cannot read property '0' of undefined
>     at Object.login (/home/autologin/vivint/vivint.js/src/request.ts:37:46)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at main (/home/autologin/vivint/vivint.js/examples/rtsp-stream.ts:6:5)

**Comment by hi019** [comment]
Looks like Vivint tweaked their authentication flow, so the script no longer works. It likely has something to do with them [deprecating their webapp](https://github.com/Riebart/vivint.py/issues/11#issuecomment-777200734). I'm open to PRs to fix this but as Riebart said, it will be more difficult to reverse engineer the Vivint API endpoints going forward
